In [1]:
import numpy as np


In [2]:
l1=[1,2,3]

In [3]:
type(l1)

list

In [4]:
np.array(l1)

array([1, 2, 3])

In [5]:
l1

[1, 2, 3]

In [6]:
type(l1)

list

In [7]:
myarr=np.array(l1)


In [8]:
type(myarr)

numpy.ndarray

In [9]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [11]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(5,2)


array([[0.45242428, 0.10521892],
       [0.68139586, 0.95043811],
       [0.54812999, 0.47772103],
       [0.15049083, 0.70755705],
       [0.25660149, 0.24329553]])

In [13]:
np.random.randn(10)

array([-2.27658421,  0.57950965,  1.3460511 ,  1.26868485,  0.59601601,
       -0.55971886,  0.72316694, -1.44232585,  0.39663251,  0.07072895])

In [14]:
arr=np.arange(0,11)


In [15]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
soa=arr[0:5]


In [20]:
soa[:]=99

In [21]:
soa

array([99, 99, 99, 99, 99])

In [22]:
a=np.arange(0,11)

In [25]:
boola=a>4

In [26]:
boola

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])