In [1]:
import numpy as np


In [2]:
arr=np.arange(0,11)

In [3]:
arr/arr

/var/folders/9p/sf1wx0t51lbgd9vn4nz_xsk40000gn/T/ipykernel_3150/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [4]:
arr.sum()

55

In [5]:
arr.std()

3.1622776601683795

In [6]:
arr.var()

10.0

In [7]:
arr.max()

10

In [8]:
arr2d=np.arange(0,25).reshape(5,5)

In [10]:
arr2d.shape

(5, 5)

In [11]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [13]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])